<header id="main-header" class="main-header">
				<a href="index.html"><img src="images/sralogo.svg"  id="logo" class="logo" href="index.html" /></a>
				<div id="text-header" class="text-header">
					<h1>Soren Rasmussen Architects Inc.</h1>
					<nav>
						<ul>
							<li><a href="about.html">About</a></li>
							<li><a href="gallery.html">Gallery</a></li>
							<li><a href="contact.html">Contact</a></li>
							<li><a href="talents.html">Talents</a></li>
						</ul>
					</nav>
				</div>
</header>
